# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  GH_TOKEN: ${{ github.token }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Check if build number file exists
        id: build_number_checker
        run: |
          $exists = "2023.2.1"
          Write-Output "EXISTS=$exists" >> $Env:GITHUB_OUTPUT

      # Runs a single command using the runners shell
      - name: test
        run: Write-Output "${{ steps.build_number_checker.outputs.EXISTS }}"

      - name: Print build number variable
        run: Write-Output "${{ vars.BUILD_NUMBER }}"

      - name: Change build number
        run: gh variable set BUILD_NUMBER --body ${{ steps.build_number_checker.outputs.EXISTS }}
