name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  dockerBuild:
    uses: ./.github/workflows/blank1.yml
  
  printBuildNumber:
    runs-on: ubuntu-latest
    needs: dockerBuild
    steps:
    - name: Test
      run: echo ${{ needs.dockerBuild.outputs.buildnumber }}

