name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:

  dockerBuild:
    uses: ./.github/workflows/blank1.yml
  
  printBuildNumber:
    runs-on: ubuntu-latest
    needs: dockerBuild
    steps:
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Pull image
      run: |
        lower=$(echo ${{ env.IMAGE_NAME }} | tr '[:upper:]' '[:lower:]')
        echo $lower
        docker pull "ghcr.io/$lower:${{ needs.dockerBuild.outputs.buildnumber }}"
