# This is a basic workflow to help you get started with Actions

name: CI - for testing cache

# Controls when the workflow will run
on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      buildnumber:
        description: "Build number"
        value: ${{ jobs.build.outputs.output1 }}
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    outputs:
      output1: ${{ steps.build_number.outputs.EXISTS }}
    permissions: write-all
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Set build number 
        id: build_number
        run: |
          $exists = "20.03.1998"
          Set-Content -Path ./.github/variables/myvars.env -Value "BUILD_NUMBER=20.03.1998."
          Write-Output "EXISTS=$exists" >> $Env:GITHUB_OUTPUT

      # Runs a single command using the runners shell
      - name: test
        run: Write-Output "${{ steps.build_number.outputs.EXISTS }}" 

      - name: Cache Dockerfile
        uses: actions/cache@v3
        with:
          key: Docker
          path: Dockerfile
      
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
    
      - name: Read cache
        uses: actions/cache@v3
        with:
          key: Docker
          path: Dockerfile
      - name: Read file
        run: cat Dockerfile
