name: SetVarsTest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Bash
        run: |
          lower=$(echo "testt")
          echo $lower

